
from app.models.product import Product


products = [
    Product(1, "Camiseta Básica", 49.90, "static/assets/productsimgs"),
    Product(2, "Calça Jeans Slim", 139.90, "static/assets/productsimgs"),
    Product(3, "Tênis Esportivo", 259.90, "static/assets/productsimgs"),
    Product(4, "Jaqueta de Couro", 349.90, "static/assets/productsimgs"),
    Product(5, "Relógio Clássico", 499.90, "static/assets/productsimgs"),
    Product(6, "Boné Estiloso", 79.90, "static/assets/productsimgs"),
    Product(7, "Óculos de Sol", 229.90, "static/assets/productsimgs"),
    Product(8, "Mochila Casual", 159.90, "static/assets/productsimgs"),
    Product(9, "Camisa Social", 119.90, "static/assets/productsimgs"),
    Product(10, "Sapato Social", 279.90, "static/assets/productsimgs"),
    Product(11, "Camiseta Estampada", 59.90, "static/assets/productsimgs"),
    Product(12, "Bermuda Jeans", 99.90, "static/assets/productsimgs"),
    Product(13, "Tênis Casual", 199.90, "static/assets/productsimgs"),
    Product(14, "Casaco Moletom", 169.90, "static/assets/productsimgs"),
    Product(15, "Pulseira de Couro", 89.90, "static/assets/productsimgs"),
    Product(16, "Carteira Masculina", 109.90, "static/assets/productsimgs"),
    Product(17, "Vestido Floral", 149.90, "static/assets/productsimgs"),
    Product(18, "Saia Jeans", 89.90, "static/assets/productsimgs"),
    Product(19, "Sandália Feminina", 129.90, "static/assets/productsimgs"),
    Product(20, "Bolsa Feminina", 199.90, "static/assets/productsimgs"),
        Product(21, "Blusa de Tricô", 129.90, "static/assets/productsimgs"),
    Product(22, "Calça de Moletom", 119.90, "static/assets/productsimgs"),
    Product(23, "Tênis de Corrida", 319.90, "static/assets/productsimgs"),
    Product(24, "Camisa Polo", 99.90, "static/assets/productsimgs"),
    Product(25, "Chinelo Confort", 49.90, "static/assets/productsimgs"),
    Product(26, "Relógio Esportivo", 399.90, "static/assets/productsimgs"),
    Product(27, "Casaco de Inverno", 389.90, "static/assets/productsimgs"),
    Product(28, "Cinto de Couro", 69.90, "static/assets/productsimgs"),
    Product(29, "Camisa Listrada", 89.90, "static/assets/productsimgs"),
    Product(30, "Blusa Cropped", 79.90, "static/assets/productsimgs"),
    Product(31, "Vestido Longo", 179.90, "static/assets/productsimgs"),
    Product(32, "Saia Midi", 119.90, "static/assets/productsimgs"),
    Product(33, "Bolsa Transversal", 149.90, "static/assets/productsimgs"),
    Product(34, "Tênis Retro", 249.90, "static/assets/productsimgs"),
    Product(35, "Boné de Aba Reta", 89.90, "static/assets/productsimgs"),
    Product(36, "Jaqueta Jeans", 219.90, "static/assets/productsimgs"),
    Product(37, "Camisa Xadrez", 99.90, "static/assets/productsimgs"),
    Product(38, "Blusa de Manga Longa", 89.90, "static/assets/productsimgs"),
    Product(39, "Shorts Esportivo", 69.90, "static/assets/productsimgs"),
    Product(40, "Moletom com Capuz", 149.90, "static/assets/productsimgs")
]